### ISSUE TITLE
Wu needs the non-stable channel of rust?

### ISSUE THREAD

**Issue by kamn** [wu-lang/wu#2]
The intro documentation just mentions having rust and just running the `cargo install`. However, you need to be on the rust nightly/beta(?) branch I think. I get the following message on the stable release channel.

```terminal
error[E0554]: #![feature] may not be used on the stable release channel
 --> src\lib.rs:1:1
  |
1 | #![feature(i128)]
  | ^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> src\lib.rs:2:1
  |
2 | #![feature(i128_type)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

Just figured I would let you know ;). Cool language btw!

**Comment by nilq** [comment]
I am very sorry for the late response, the notification must've drowned. :(( 

Those lines were added somewhat after I wrote documentation; I totally forgot about this as I'm always working on nightly. Thanks a lot for pointing out, I will keep this in mind when writing the new documentation.

I'm glad you like Wu and thanks for taking the time to submit an issue!

xx

**Comment by nilq** [comment]
This is now fixed!
