### ISSUE TITLE
Github sponsor issue

### ISSUE THREAD

**Issue by pims** [wu-lang/wu#24]
Hi,

I was trying to sponsor this very neat project but got prompted with an error

<img width="435" alt="Screen Shot 2020-06-30 at 10 38 17 AM" src="https://user-images.githubusercontent.com/27320/86158659-f62dbf80-babd-11ea-9d79-5d540e89aa6e.png">

I think the `funding.yml` is missing a few required fields:
```
github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
```

<img width="700" alt="funding-yml-file" src="https://user-images.githubusercontent.com/27320/86158802-2bd2a880-babe-11ea-9334-6f3d99be330e.png">

**Comment by evolbug** [comment]
Hey @pims, looks like some things got messed up with Nilq's sponsor details, the file itself is fine. This should be resolved soon-ish I believe

**Comment by nilq** [comment]
Good day, @pims! Thank you for addressing this and for trying to sponsor Wu. I added the Sponsor button a little too early, as the my GitHub Sponsor profile is still pending.

It should be approved within the next few days 😄

**Comment by nilq** [comment]
We've approved 😄
