### ISSUE TITLE
[bug] implement parse failures

### ISSUE THREAD

**Issue by evolbug** [wu-lang/wu#31]
Several failures: 
- block is ignored if there is a keyword between two user types
```rs
Test: struct {}
implement Test if Test {}
``` 
- parse fails if there's a newline in implement block body but no method 
```rs
Test: struct {}
implement Test: Test {
}
```
- implement accepts Type in place of Trait
```rs
Test: struct {}
implement Test: Test {
    foo: fun() {}
}
```
- parse fails if there's extraneous newlines after method
```rs
implement Data: Data_T {
    clone:          extern fun(self) -> Data

}
```

**Comment by nilq** [comment]
Yessir.
