### ISSUE TITLE
Compile to LuaJIT bytecode?

### ISSUE THREAD

**Issue by hengestone** [wu-lang/wu#40]
For speed!

If you think this is is something you can take on, let's talk!

**Comment by evolbug** [comment]
Currently the user can pick their own Lua runtime as they wish, since Wu targets the core syntax of Lua 5.1. Not sure there's any benefit for us to generate the bytecode ourselves

**Comment by hengestone** [comment]
The benefit is that the source <--> bytecode connection remains intact, making e.g. debugging more straightforward. :)
