### ISSUE TITLE
wu.toml not working properly?

### ISSUE THREAD

**Issue by darltrash** [wu-lang/wu#42]
I have a wu.toml file like this:
![imagen](https://user-images.githubusercontent.com/38925212/117524153-50bf6400-af8a-11eb-9fe7-94d48a34a9cb.png)
but i get:
![imagen](https://user-images.githubusercontent.com/38925212/117524165-60d74380-af8a-11eb-8f5d-5826bb3cb7b2.png)
Am I meant to use it this way?

**Comment by nilq** [comment]
Hello! This surely needs same more thorough documentation. `wu.toml` requires TOML values definitions, so your file should contain the following instead:

```toml
[dependencies]
std = "wu-lang/std"
```

I hope this solves it.

**Comment by darltrash** [comment]
> ```toml
> [dependencies]
> std = "wu-lang/std"
> ```

It seems like it worked! ...but not properly yet
![imagen](https://user-images.githubusercontent.com/38925212/117592634-51313980-b107-11eb-8ce6-5c64081c2ca9.png)
Im not trying to write it onto any special or protected place (like /, for example) yet it would still happen

**Comment by nilq** [comment]
Ah right! I just pushed a possible fix. :smile:
