### ISSUE TITLE
Consider updating the readme?

### ISSUE THREAD

**Issue by Calandiel** [wu-lang/wu#49]
It hasn't been changed in over two years. To quote it:
```
Wu is built and maintained by a minimal team of people and was primarily developed during boring primary school classes, to help make time pass faster. Currently being maintained by an 18-year-old.
```
I think "currently being maintained by an 18-year-old" sounds very weird in a github repository. Are we meant to treat it as a request to not use it for anything serious? If we are, that's in contradiction with tongue-in-cheek `You are using it` on the selling points list just above it.
It's the kind of remark that could only hurt adoption of the project, imho. Not to mention that it's not even true anymore since time (sadly) doesn't stay constant. I'd suggest dropping that whole disclaimer altogether, the language works, it's irrelevant how it came to be ^^

**Comment by evolbug** [comment]
That is a fair assessment, the whimsical readme does imply it's not a 100% serious project, I wouldn't program your grandma's pacemaker with it, but it's neat for small projects. We've been quite busy these past years so it hasn't had updates, although one of us will occasionally fix things when we have time. 

We may do more with it in the future, though at the moment it isn't fully active, I've updated the disclaimer to reflect that.
